### ISSUE TITLE
ADC specification and configuration

### ISSUE THREAD

**Issue by DurandA** [dbuezas/arduino-web-oscilloscope#4]
Hi David,

First of all, thank you for this awesome project. I discovered it via Hackaday and had a LGT328P board laying around.

I have a few questions reguarding the ADC readings of the LGT328P.

1. I had a quick look at the english datasheet and it mentions that the ADC `Sampling rate can reach to 5000KSPSat highest resolution` which is translated from `最高分辨率时采样率高达500KSPS` so I guess there is a typo and it can sample at 500 kSPS. Is this consistent with what you can read from the firmware?
2. Is the ADC value compared to VCC or internal voltage references? What happens if the LGT328P is powered with 3.3V?
3. What is `AS`? Is it supposed to be `A1`? Also the README mentions `A1` while the software uses `A0`.
4.  What is the [`arduino analog2`](https://github.com/dbuezas/arduino-web-oscilloscope/tree/master/arduino%20analog2) folder?
5. There are some strange readings when generating a signal from 0 to 4V (e.g. a sine; see screenshot below). This does not happens when generating a signal from 0 to 5V. Do you have any idea of what is happening? Do you switch between voltage references?

![4V sine](https://user-images.githubusercontent.com/3709037/108874337-5a2c6780-75fc-11eb-9175-dc22feb8ea39.png)

Thanks!

**Comment by dbuezas** [comment]
Thanks for the kind words! @DurandA!
1. Yes, the max sampling rate is actually around 734kSamples/s, but the ADC gets so little time to measure that the readings get capped at 3v at those speeds. You'll need to chose a slower speed (use the left-right arrows) or change the volts/division (up-down keys) for it to read up to 5v.
2. Yes, reference voltage is AVCC (see [here](https://github.com/dbuezas/arduino-web-oscilloscope/blob/master/arduino/src/adc.h#L49) ). I haven't tried it at 3.3v but I believe it will also limit the readings. You can change the volts per division or just add an external voltage divider to mitigate that a bit.
4. The arduino analog2 folder is the code to plug a secondary board. The 2nd ADC constantly measures and the value is transferred in parallel through 8 digital channels. I didn't document that because it is a bit of a mess to connect 8 cables across + 1 for serial communication. 
3. that's what "AS" is for. "A-Secondary". You can also enable XY mode with that. 
I planned to port the code to the STM32, which has 2 ADCs and can reach 2MSamples/s but I never got to it. Maybe now that people seem to like this (thanks to hackaday ❤️ ) I'll get back to this project.
5. see (1) if you go below 101us/division, the ADC prescaler is set to the minimum and with the CPU at 32Mhz, the ADC really struggles to measure above 3v. When you set the volts/division higher, there's an internal voltage divider so the ADC is actually reading lower voltages and this is somewhat compensated for.

**Comment by DurandA** [comment]
Many thanks for your detailed answer.

This LGT328P is quite interesting. Did you know it can push 80mA on 6 pins? Also I wonder if the faster 12-bit ADC could be used to improve the famous AVR transistor tester (see https://www.mikrocontroller.net/articles/AVR_Transistortester). Do you know if the ADC response is linear?

Also your web frontend is a great inspiration to control electronics. I am tinkering with something similar to [control a hot plate using the Web Bluetooth API](https://github.com/DurandA/reflow946).

**Comment by dbuezas** [comment]
Yes I [knew](https://github.com/dbuezas/lgt8fx/issues/21#issuecomment-657020605) about the 80mA pins, it's quite a nice detail!, I like the chip a lot :)
The response of the ADC is linear as long as you don't get too close to the 5v rail. I made a pitch shifter with this board (it also has an unbuffered DAC) and the resulting audio is surprisingly clear. 

I like your idea about the transistor tester, it would be quite an interesting project to port it to this board for the extra 2 bits of precision and even lower cost.
You may want to consider posting the idea in [here](https://github.com/dbuezas/lgt8fx/discussions) the mini community is quite active and full of smarts!

Thanks again for your kind words :), that's quite an interesting project you have there, I believe that having a full UI for some hardware without having to install anything is quite a powerful concept, particularly when this gets ported to mobile devices.
